packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # Framework
  hono: ^4.7.14

  # GraphQL
  graphql: ^16.9.0
  graphql-yoga: ^5.10.6
  '@pothos/core': ^4.3.0
  '@pothos/plugin-validation': ^4.1.0

  # Database
  drizzle-orm: ^0.39.3
  drizzle-kit: ^0.31.3
  postgres: ^3.4.5

  # Build & Dev Tools
  tsx: ^4.19.2
  tsup: ^8.3.5
  typescript: ^5.7.3

  # Testing
  vitest: ^2.1.8

  # Types
  '@types/node': ^22.10.5
