// Extended patient data for detail view
export const patientDetails = {
  P001: {
    demographics: {
      fullName: "Michael Chen",
      dob: "1985-03-15",
      age: 40,
      gender: "Male",
      ssn: "***-**-4567",
      address: "123 Oak Street, San Francisco, CA 94102",
      email: "michael.chen@email.com",
      phone: "(555) 123-4567",
      emergencyContact: "Lisa Chen (Wife) - (555) 123-4568",
    },
    insurances: [
      {
        id: "INS-001",
        provider: "Blue Cross Blue Shield",
        type: "Primary",
        memberId: "BCBS123456789",
        groupNumber: "GRP-001",
        copay: 25,
        deductible: 1500,
        deductibleMet: 800,
        effectiveDate: "2025-01-01",
        expirationDate: "2025-12-31",
        status: "Active",
      },
    ],
    pastVisits: [
      {
        date: "2025-09-15",
        provider: "Dr. Sarah Johnson",
        reason: "Annual Physical",
        diagnosis: "Routine examination - No issues",
        amount: 250.0,
        paid: 250.0,
      },
      {
        date: "2025-06-10",
        provider: "Dr. Michael Roberts",
        reason: "Follow-up - Lab Results",
        diagnosis: "Cholesterol management",
        amount: 150.0,
        paid: 150.0,
      },
      {
        date: "2025-03-20",
        provider: "Dr. Sarah Johnson",
        reason: "Flu Symptoms",
        diagnosis: "Viral infection",
        amount: 120.0,
        paid: 120.0,
      },
    ],
    bills: [
      {
        id: "BILL-001",
        date: "2025-09-15",
        description: "Annual Physical Examination",
        amount: 250.0,
        paid: 250.0,
        balance: 0,
        status: "Paid",
      },
    ],
    referrals: [
      {
        date: "2025-09-15",
        referredTo: "Dr. James Wilson - Cardiology",
        reason: "Preventive cardiac screening",
        status: "Pending",
      },
    ],
    medications: [
      {
        name: "Atorvastatin 20mg",
        dosage: "Once daily",
        prescribedBy: "Dr. Michael Roberts",
        prescribedDate: "2025-06-10",
        refills: 3,
      },
    ],
    labs: [
      {
        date: "2025-09-10",
        test: "Lipid Panel",
        results: "Total Cholesterol: 195 mg/dL (Normal)",
        orderedBy: "Dr. Sarah Johnson",
      },
      {
        date: "2025-09-10",
        test: "Complete Blood Count",
        results: "All values within normal range",
        orderedBy: "Dr. Sarah Johnson",
      },
    ],
  },
  P002: {
    demographics: {
      fullName: "Jennifer Martinez",
      dob: "1972-07-22",
      age: 53,
      gender: "Female",
      ssn: "***-**-5678",
      address: "456 Maple Avenue, Oakland, CA 94601",
      email: "j.martinez@email.com",
      phone: "(555) 234-5678",
      emergencyContact: "Carlos Martinez (Husband) - (555) 234-5679",
    },
    insurances: [
      {
        id: "INS-002",
        provider: "Aetna",
        type: "Primary",
        memberId: "AET987654321",
        groupNumber: "GRP-002",
        copay: 30,
        deductible: 2000,
        deductibleMet: 1200,
        effectiveDate: "2025-01-01",
        expirationDate: "2025-12-31",
        status: "Active",
      },
    ],
    pastVisits: [
      {
        date: "2025-08-15",
        provider: "Dr. Sarah Johnson",
        reason: "Hypertension Management",
        diagnosis: "Essential hypertension",
        amount: 180.0,
        paid: 0,
      },
      {
        date: "2025-07-10",
        provider: "Dr. Sarah Johnson",
        reason: "Follow-up - Blood Pressure",
        diagnosis: "Hypertension - adjusting medication",
        amount: 150.0,
        paid: 0,
      },
      {
        date: "2025-05-20",
        provider: "Dr. Sarah Johnson",
        reason: "Initial Consultation",
        diagnosis: "Newly diagnosed hypertension",
        amount: 220.0,
        paid: 100.0,
      },
    ],
    bills: [
      {
        id: "BILL-002",
        date: "2025-08-15",
        description: "Hypertension Management Visit",
        amount: 180.0,
        paid: 0,
        balance: 180.0,
        status: "Overdue",
      },
      {
        id: "BILL-003",
        date: "2025-07-10",
        description: "Follow-up Visit",
        amount: 150.0,
        paid: 0,
        balance: 150.0,
        status: "Overdue",
      },
      {
        id: "BILL-004",
        date: "2025-05-20",
        description: "Initial Consultation",
        amount: 220.0,
        paid: 100.0,
        balance: 120.0,
        status: "Partial",
      },
    ],
    referrals: [],
    medications: [
      {
        name: "Lisinopril 10mg",
        dosage: "Once daily",
        prescribedBy: "Dr. Sarah Johnson",
        prescribedDate: "2025-08-15",
        refills: 5,
      },
      {
        name: "Hydrochlorothiazide 25mg",
        dosage: "Once daily",
        prescribedBy: "Dr. Sarah Johnson",
        prescribedDate: "2025-07-10",
        refills: 5,
      },
    ],
    labs: [
      {
        date: "2025-08-10",
        test: "Basic Metabolic Panel",
        results: "Sodium, Potassium within normal limits",
        orderedBy: "Dr. Sarah Johnson",
      },
    ],
  },
}

export type PatientId = keyof typeof patientDetails
